"""Added issue reports

Revision ID: 11f15ef1111b
Revises: a6090717d12d
Create Date: 2026-03-21 15:46:12.916033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11f15ef1111b'
down_revision: Union[str, Sequence[str], None] = 'a6090717d12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuereport',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_RESPONSE', 'SELLER_RESPONDED', 'RESOLVED', name='reportstatus'), nullable=False),
    sa.Column('seller_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['bundleposting.posting_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['consumer.user_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_issuereport_issue_id'), 'issuereport', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issuereport_posting_id'), 'issuereport', ['posting_id'], unique=False)
    op.create_index(op.f('ix_issuereport_user_id'), 'issuereport', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issuereport_user_id'), table_name='issuereport')
    op.drop_index(op.f('ix_issuereport_posting_id'), table_name='issuereport')
    op.drop_index(op.f('ix_issuereport_issue_id'), table_name='issuereport')
    op.drop_table('issuereport')
    # ### end Alembic commands ###
