"""initial setup

Revision ID: 4250a46bca0e
Revises: 
Create Date: 2026-02-08 11:13:49.836445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4250a46bca0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'CONSUMER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('bundleposting',
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('BAKED_GOODS', 'FRUIT', 'VEGETABLES', 'MEAT', 'SEAFOOD', 'SNACKS', 'DAIRY', 'DRINKS', name='category'), nullable=False),
    sa.Column('allergens', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('pickup_window', postgresql.TSTZRANGE(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD_OUT', 'EXPIRED', 'DELETED', name='bundlestatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('posting_id')
    )
    op.create_index(op.f('ix_bundleposting_pickup_window'), 'bundleposting', ['pickup_window'], unique=False)
    op.create_index(op.f('ix_bundleposting_posting_id'), 'bundleposting', ['posting_id'], unique=False)
    op.create_index(op.f('ix_bundleposting_user_id'), 'bundleposting', ['user_id'], unique=False)
    op.create_table('consumer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_consumer_user_id'), 'consumer', ['user_id'], unique=False)
    op.create_table('seller',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opening_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_seller_user_id'), 'seller', ['user_id'], unique=False)
    op.create_table('forecast',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('predicted_reservations', sa.Integer(), nullable=False),
    sa.Column('predicted_no_show_prob', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['bundleposting.posting_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecast_forecast_id'), 'forecast', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecast_posting_id'), 'forecast', ['posting_id'], unique=False)
    op.create_index(op.f('ix_forecast_user_id'), 'forecast', ['user_id'], unique=False)
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('pickup_window', postgresql.TSTZRANGE(), nullable=True),
    sa.Column('category', sa.Enum('BAKED_GOODS', 'FRUIT', 'VEGETABLES', 'MEAT', 'SEAFOOD', 'SNACKS', 'DAIRY', 'DRINKS', name='category'), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('raining', sa.Boolean(), nullable=False),
    sa.Column('observed_reservations', sa.Integer(), nullable=False),
    sa.Column('observed_no_show', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['bundleposting.posting_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_record_pickup_window'), 'record', ['pickup_window'], unique=False)
    op.create_index(op.f('ix_record_posting_id'), 'record', ['posting_id'], unique=False)
    op.create_index(op.f('ix_record_record_id'), 'record', ['record_id'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'COLLECTED', 'NO_SHOW', name='reservationstatus'), nullable=False),
    sa.Column('claim_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['bundleposting.posting_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_reservation_claim_code'), 'reservation', ['claim_code'], unique=True)
    op.create_index(op.f('ix_reservation_posting_id'), 'reservation', ['posting_id'], unique=False)
    op.create_index(op.f('ix_reservation_reservation_id'), 'reservation', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_user_id'), 'reservation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_user_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_reservation_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_posting_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_claim_code'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_record_id'), table_name='record')
    op.drop_index(op.f('ix_record_posting_id'), table_name='record')
    op.drop_index(op.f('ix_record_pickup_window'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_forecast_user_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_posting_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_forecast_id'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_seller_user_id'), table_name='seller')
    op.drop_table('seller')
    op.drop_index(op.f('ix_consumer_user_id'), table_name='consumer')
    op.drop_table('consumer')
    op.drop_index(op.f('ix_bundleposting_user_id'), table_name='bundleposting')
    op.drop_index(op.f('ix_bundleposting_posting_id'), table_name='bundleposting')
    op.drop_index(op.f('ix_bundleposting_pickup_window'), table_name='bundleposting')
    op.drop_table('bundleposting')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
