"""Added weight and observed_expired

Revision ID: 5d15a5c5fb4a
Revises: 5085c48af07e
Create Date: 2026-02-17 15:16:17.881343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d15a5c5fb4a'
down_revision: Union[str, Sequence[str], None] = '5085c48af07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundleposting', sa.Column('weight', sa.Integer(), nullable=False))
    op.add_column('record', sa.Column('observed_expired', sa.Integer(), nullable=False))
    op.add_column('record', sa.Column('weight', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'weight')
    op.drop_column('record', 'observed_expired')
    op.drop_column('bundleposting', 'weight')
    # ### end Alembic commands ###
