"""Added categories table

Revision ID: 67ab9eb90cfe
Revises: 986c6861eef0
Create Date: 2026-03-20 10:16:35.410288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67ab9eb90cfe'
down_revision: Union[str, Sequence[str], None] = '986c6861eef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.add_column('bundleposting', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bundleposting', 'categories', ['category_id'], ['category_id'])
    op.drop_column('bundleposting', 'category')
    op.add_column('record', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'record', 'categories', ['category_id'], ['category_id'])
    op.drop_column('record', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('category', postgresql.ENUM('BAKED_GOODS', 'FRUIT', 'VEGETABLES', 'MEAT', 'SEAFOOD', 'SNACKS', 'DAIRY', 'DRINKS', name='category'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'category_id')
    op.add_column('bundleposting', sa.Column('category', postgresql.ENUM('BAKED_GOODS', 'FRUIT', 'VEGETABLES', 'MEAT', 'SEAFOOD', 'SNACKS', 'DAIRY', 'DRINKS', name='category'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bundleposting', type_='foreignkey')
    op.drop_column('bundleposting', 'category_id')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
