"""Added logo urls to sellers

Revision ID: 744ed8fe585e
Revises: 11f15ef1111b
Create Date: 2026-03-22 16:21:23.876834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '744ed8fe585e'
down_revision: Union[str, Sequence[str], None] = '11f15ef1111b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="https://res.cloudinary.com/dnbeji59a/image/upload/v1774196127/profile-picture-blank_nnm3vq.jpg"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'logo_url')
    # ### end Alembic commands ###
