"""Added badge and consumer badge tables

Revision ID: 986c6861eef0
Revises: 892d131a3e14
Create Date: 2026-03-18 17:37:41.031439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '986c6861eef0'
down_revision: Union[str, Sequence[str], None] = '892d131a3e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_index(op.f('ix_badge_badge_id'), 'badge', ['badge_id'], unique=False)
    op.create_table('consumerbadge',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.badge_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['consumer.user_id'], ),
    sa.PrimaryKeyConstraint('badge_id', 'user_id')
    )
    op.create_index(op.f('ix_consumerbadge_user_id'), 'consumerbadge', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumerbadge_user_id'), table_name='consumerbadge')
    op.drop_table('consumerbadge')
    op.drop_index(op.f('ix_badge_badge_id'), table_name='badge')
    op.drop_table('badge')
    # ### end Alembic commands ###
