"""Added initial price and contents to bundlePosting

Revision ID: ca5fb0b05b07
Revises: 744ed8fe585e
Create Date: 2026-03-23 16:00:41.866733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca5fb0b05b07'
down_revision: Union[str, Sequence[str], None] = '744ed8fe585e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundleposting', sa.Column('initial_price', sa.NUMERIC(precision=10, scale=2), nullable=True, server_default='10'))
    op.add_column('bundleposting', sa.Column('contents', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default= "temp content"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundleposting', 'contents')
    op.drop_column('bundleposting', 'initial_price')
    # ### end Alembic commands ###
